# This file is to store parameters for monthly usage reporting

dataSourceMapping = {
	'twitter' 	 	: { 'type' : 'Data Source', 'label' : 'Twitter' },
	'facebook'	 	: { 'type' : 'Data Source', 'label' : 'Facebook' },
	'bitly_trial'		: { 'type' : 'Data Source', 'label' : 'Bitly' },
	'amazon'	 	: { 'type' : 'Data Source', 'label' : 'Amazon' },
	'2ch'		 	: { 'type' : 'Data Source', 'label' : '2ch' },
	'blog'		 	: { 'type' : 'Data Source', 'label' : 'Blog' },
	'board'		 	: { 'type' : 'Data Source', 'label' : 'Board' },
	'dailymotion'		: { 'type' : 'Data Source', 'label' : 'Dailymotion' },
	'demographics'		: { 'type' : 'Data Source', 'label' : 'Demographics' },
	'demographics_trial' 	: { 'type' : 'Data Source', 'label' : 'Demographics' },
	'digg'			: { 'type' : 'Data Source', 'label' : 'Digg' },
	'flickr'		: { 'type' : 'Data Source', 'label' : 'Flickr' },
	'imdb'			: { 'type' : 'Data Source', 'label' : 'IMDb' },
	'intensedebate'		: { 'type' : 'Data Source', 'label' : 'Intense Debate' },
	'intensedebate_perinteraction' : { 'type' : 'Data Source', 'label' : 'Intense Debate' },
	'klout.profile'		: { 'type' : 'Augmentation', 'label' : 'Klout Profile' },
	'klout_topics'		: { 'type' : 'Augmentation', 'label' : 'Klout Topics' },
	'klout.topics'		: { 'type' : 'Augmentation', 'label' : 'Klout Topics' },
	'lexisnexis'		: { 'type' : 'Data Source', 'label' : 'Lexis Nexis' },
	'lexisnexis_perinteraction' : { 'type' : 'Data Source', 'label' : 'Lexis Nexis' },
	'links'			: { 'type' : 'Augmentation', 'label' : 'Links' },
	'myspace'		: { 'type' : 'Data Source', 'label' : 'MySpace' },
	'newscred_perinteraction' : { 'type' : 'Data Source', 'label' : 'Newscred' },
	'reddit'		: { 'type' : 'Data Source', 'label' : 'Reddit' },
	'salience.entities'	: { 'type' : 'Augmentation', 'label' : 'Salience Entities' },
	'salience.sentiment'	: { 'type' : 'Augmentation', 'label' : 'Salience Sentiment' },
	'salience.topics'	: { 'type' : 'Augmentation', 'label' : 'Salience Topics' },
	'sentiment.topics'	: { 'type' : 'Augmentation', 'label' : 'Sentiment Topics' },
	'sinaweibo_perinteraction' : { 'type' : 'Augmentation', 'label' : 'Sina Weibo' },
	'tancentweibo_perinteraction' : { 'type' : 'Augmentation', 'label' : 'Tancent Weibo' },
	'topix'			: { 'type' : 'Data Source', 'label' : 'Topix' },
	'trends'		: { 'type' : 'Augmentation', 'label' : 'Trends' },
	'tumblr'		: { 'type' : 'Data Source', 'label' : 'Tumblr' },
	'video'			: { 'type' : 'Data Source', 'label' : 'Video' },
	'wordpress.blog'	: { 'type' : 'Data Source', 'label' : 'Wordpress Blog' },
	'wordpress.comment'	: { 'type' : 'Data Source', 'label' : 'Wordpress Comment' },
	'youtube'		: { 'type' : 'Data Source', 'label' : 'YouTube' },
}

dataDirectory = "reporting/data"
